config/routes.rb
Hw1::Application.routes.draw do
  get "system_entry/soptions"
  get "system_entry/list"
  get "system_entry/map"

  resources :people do
    collection do
      get 'list'
      get 'soptions'
      get 'map'
    end
  end

end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :Last, :First, :Pin, :Zip, :Longitude, :Latitude, :City, :State, :Region, :Address, :Country


    validates :Last,      :presence => true,
                          :length   => { :maximum => 50 }

    validates :First,     :presence => true,
                          :length   => { :maximum => 50}

    validates :Region,    :length => { :maximum => 50 }

    validates :Country,   :length => { :maximum => 50 }

    validates :Zip,       :length => { :within => 0..5 }

    validates :Longitude, :length => { :maximum => 180, :greater_than => -180 }

    validates :Latitude,  :length => { :maximum => 90 , :greater_than =>- 90}

    validates :Pingit , :presence     => true,
                          :confirmation => true,
                          :length       => { :within => 1..3 }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
   include Geokit::Geocoders
  # GET /people
  # GET /people.xml
  def list
    @people = Person.all

    respond_to do |format|
      format.html # list.html.erb
      format.xml  { render :xml => @people }
    end
  end

  # GET /people/1
  # GET /people/1.xml
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @person }
    end
  end

  # GET /people/index
  # GET /people/index.xml
  def index
    @person = Person.new
    if cookies[:user_id] != nil
      @person = Person.where(:id => cookies[:user_id].to_i)
      if @person != nil
        session[:sid] = cookies[:user_id]
        redirect_to :action => "soptions"
        return
      end
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  def map
    @people = Person.all

    @people.each do |person|
      if person.Latitude.empty?
        if not person.Address.empty?
          @address = MultiGeocoder.geocode(person.Address + ' ' + person.City + ', ' + person.State)
          person.Latitude=@address.lat
          person.Longitude=@address.lng
        end
        if not person.Zip.empty?
          @city = MultiGeocoder.geocode(person.Zip)
          person.Latitude=@city.lat
          person.Longitude=@city.lng
        end

        if person.Zip.empty? & person.Address.empty?
          @ip = MultiGeocoder.geocode(request.remote_ip)
          person.Latitude=@ip.lat
          person.Longitude=@ip.lng
        end
      end
    end
  end

  # POST /people
  # POST /people.xml
  def create
    @person = Person.new(params[:person])
    respond_to do |format|

      if @person.save
        #create cookies
        cookies[:user_id] = {:value => @person.id.to_s, :expires => Time.now + 30000}
        cookies[:user_name] = {:value => params[:person][:last], :expires => Time.now + 30000}
        cookies[:full_address] = {:value => params[:person][:address], :expires => Time.now + 30000}
        format.html { redirect_to :action => 'soptions' }
        format.xml  { render :xml => @person, :status => :created, :location => @person }
      else
        format.html { render :action => "index" }
        format.xml  { render :xml => @person.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.xml
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to(@person, :notice => 'Person was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @person.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.xml
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to(people_url) }
      format.xml  { head :ok }
    end
  end

  def soptions
    @person = Person.find_by_id(Person.where(:id => cookies[:user_id].to_i))
    #Converting addresses and IP's to lat long for the map'
    respond_to do |format|
      format.html # list.html.erb      format.xml  { render :xml => @people }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hw1</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= stylesheet_link_tag  "random" %>
<%= javascript_include_tag 'jquery', 'test' %>



<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :Last %><br />
    <%= f.text_field :Last %>
  </div>
  <div class="field">
    <%= f.label :First %><br />
    <%= f.text_field :First %>
  </div>
  <div class ="field" align="left" id="radiobuttons"><br>


        How would you like to be located? <br>
        <input type="radio" name="group1" id="longlat" value="1"> Longitude & Latitude<br>
        <input type="radio" name="group1" id="saddress" value="2" > Street Address<br>
        <input type="radio" name="group1" id="citystate" value="3"> Zip Code<br>
        <input type="radio" name="group1" id="ip" value="4"> IP Address<br><br>


  </div>
  <div class="field">
    <%= f.label :Pin %><br />
    <%= f.text_field :Pin %>
  </div>
  <div class="field" id="long">
    <%= f.label :Longitude %><br />
    <%= f.text_field :Longitude %>
    Must be between -180 and 80
  </div>
  <div class="field" id="lat">
    <%= f.label :Latitude %><br />
    <%= f.text_field :Latitude %>
    Must be between -90 and 90
  </div>
  <div class="field" id="address">
    <%= f.label :Address %><br />
    <%= f.text_field :Address %>
  </div>
  <div class="field" id="city">
    <%= f.label :City %><br />
    <%= f.text_field :City %>
  </div>
  <div class="field" id="region">
    <%= f.label :Region %><br />
    <%= f.text_field :Region %>
  </div>
  <div class="field" id="state">
    <%= f.label :State %><br />
    <%= f.text_field :State %>
  </div>
  <div class="field" id="zip">
    <%= f.label :Zip %><br />
    <%= f.text_field :Zip %>
  </div>
  <div class="field" id="country">
    <%= f.label :Country %><br />
    <%= f.text_field :Country %>
  </div>
  <div class="actions" id="submit">
    Code is correct, please click "Create Person" <br />
    <%= f.submit %>
  </div>

<BR><BR>

<p id="randomnumber">
    <% @random_number = rand(9999) + 10000
        session[:random_num] = @random_n1
        @string_random = @random_number.to_s
        i=0

        %>

        <script>
          var random_num = "<%= @string_random %>"
        </script>

        <%
        loop do
            i+=1
            @random_n1 = rand(10)
            @dig = @string_random[i-1]
            break if i==6

            @class = "s1"

            if @random_n1 >= 2
                @class = "s2"
            end

            if @random_n1 >= 5
                @class = "s3"
            end

            if @random_n1 >= 7
                @class = "s4"
            end
            %>
            <span class='<%= @class %>'> <%= @dig %> </span>
        <% end %>
    <br>

</p>
<div id="sec_question">

<input type="textbox" name="group1" id="sec_code" value="">
    <a id="code">Check</a>
    <br>Enter the security number above and click "Check"<br>
</div>
<script>
  $("#long").hide()
  $("#lat").hide()
  $("#address").hide()
  $("#city").hide()
  $("#state").hide()
  $("#zip").hide()
  $("#country").hide()
  $("#region").hide()

  //Hiding the submit button until the number entered is correct
  $("#submit").hide()
  //Check number when button is clicked
  $("#code").click(function() {
    if ($("#sec_code").val() == random_num) {
        $("#submit").show();
        $("#sec_question").hide();
        $("#randomnumber").hide();
    }
    else {
        alert("The code you entered is incorrect, please try again");
        window.location.reload() //Loading a new number if the user entered the other one wrong
    }
  });

  //Checking to see which radio button has been checked
  $("#radiobuttons input:radio").click(function() {
    if ($(this).val() === "1") {
        $("#long").show();
        $("#lat").show();
        $("#address").hide();
        $("#city").hide();
        $("#state").hide();
        $("#zip").hide();
        $("#country").hide();
        $("#region").hide();
    }
    if ($(this).val() === "2") {
        $("#long").hide();
        $("#lat").hide();
        $("#address").show();
        $("#city").show();
        $("#state").show();
        $("#zip").hide();
        $("#country").show();
        $("#region").show();
    }
    if ($(this).val() === "3") {
        $("#long").hide();
        $("#lat").hide();
        $("#address").hide();
        $("#city").hide();
        $("#state").hide();
        $("#zip").show();
        $("#country").show();
        $("#region").show();
    }
    if ($(this).val() === "4") {
        $("#long").hide();
        $("#lat").hide();
        $("#address").hide();
        $("#city").hide();
        $("#state").hide();
        $("#zip").hide();
        $("#country").hide();
        $("#region").hide();
    }
  });
</script>
<%end%>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/list.html.erb
<h1>Listing people</h1>

<table>
  <tr>
    <th>Last</th>
    <th>First</th>
    <th>Pin</th>
    <th>Longitude</th>
    <th>Latitude</th>
    <th>Address</th>
    <th>City</th>
    <th>Region</th>
    <th>State</th>
    <th>Zip</th>
    <th>Country</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= person.Last %></td>
    <td><%= person.First %></td>
    <td><%= person.Pin %></td>
    <td><%= person.Longitude %></td>
    <td><%= person.Latitude %></td>
    <td><%= person.Address %></td>
    <td><%= person.City %></td>
    <td><%= person.Region %></td>
    <td><%= person.State %></td>
    <td><%= person.Zip %></td>
    <td><%= person.Country %></td>
    <td><%= link_to 'Destroy', person, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Back', soptions_people_path %>

app/views/people/map.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  <title>Google Maps Multiple Markers</title>
  <script src="http://maps.google.com/maps/api/js?sensor=false"
          type="text/javascript"></script>
</head>
<body>
    <h1>Viewing Map</h1>
  <div id="map" style="width: 500px; height: 400px;"></div>
  <script type="text/javascript">

    var locations = [
    //Showing location by latitude and longitude
        <% @people.each do |person| %>
        ['<%= person.Pin %>', <%= person.Latitude %>, <%= person.Longitude %>],
        <%end%>
    ];
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 1,
      center: new google.maps.LatLng(42.92, -88.25),
      mapTypeId: google.maps.MapTypeId.ROADMAP
    });

    var infowindow = new google.maps.InfoWindow();

    var marker, i;

    for (i = 0; i < locations.length; i++) {
      marker = new google.maps.Marker({
        position: new google.maps.LatLng(locations[i][1], locations[i][2]),
        map: map
      });

      google.maps.event.addListener(marker, 'click', (function(marker, i) {
        return function() {
          infowindow.setContent(locations[i][0]);
          infowindow.open(map, marker);
        }
      })(marker, i));
    }
  </script>
  <%= link_to 'Back', people_path %>
</body>
</html>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Last:</b>
  <%= @person.Last %>
</p>

<p>
  <b>First:</b>
  <%= @person.First %>
</p>

<p>
  <b>Pin:</b>
  <%= @person.Pin %>
</p>

<p>
  <b>Longitude:</b>
  <%= @person.Longitude %>
</p>

<p>
  <b>Latitude:</b>
  <%= @person.Latitude %>
</p>

<p>
  <b>Address:</b>
  <%= @person.Address %>
</p>

<p>
  <b>City:</b>
  <%= @person.City %>
</p>

<p>
  <b>Region:</b>
  <%= @person.Region %>
</p>

<p>
  <b>State:</b>
  <%= @person.State %>
</p>

<p>
  <b>Zip:</b>
  <%= @person.Zip %>
</p>

<p>
  <b>Country:</b>
  <%= @person.Country %>
</p>

<%= link_to 'Home', people_path %>

app/views/people/soptions.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>Choose what to do next</b><br/>
  <%= link_to 'List People', list_people_path %><br>
  <%= link_to 'Edit Profile', edit_person_path(@person) %><br>
  <%= link_to 'View Map', map_people_path %>
</p>